export type IntegrationCategory =
  | "ai"
  | "communication"
  | "productivity"
  | "database"
  | "developer";

export type IntegrationAuthType = "oauth" | "apikey" | "none";

export interface OAuthConfig {
  authorizationUrl: string;
  tokenUrl: string;
  scopes: string[];
  clientIdEnv: string;
  clientSecretEnv: string;
  tokenExchange: "body" | "basic_auth";
  additionalAuthParams?: Record<string, string>;
}

export interface IntegrationDefinition {
  slug: string;
  name: string;
  description: string;
  category: IntegrationCategory;
  authType: IntegrationAuthType;
  color: string;
  bgColor: string;
  iconText: string;
  oauthConfig?: OAuthConfig;
  apiKeyLabel?: string;
  apiKeyPlaceholder?: string;
  docsUrl?: string;
}

export const INTEGRATIONS: IntegrationDefinition[] = [
  // ── AI ───────────────────────────────────────────────────────────────────
  {
    slug: "openai",
    name: "OpenAI",
    description: "Connect GPT-4, DALL·E, and other OpenAI models to generate text, images, and more.",
    category: "ai",
    authType: "apikey",
    color: "#10b981",
    bgColor: "#052e16",
    iconText: "AI",
    apiKeyLabel: "OpenAI API Key",
    apiKeyPlaceholder: "sk-...",
    docsUrl: "https://platform.openai.com/api-keys",
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    description: "Use Claude models for reasoning, summarization, coding, and complex multi-step tasks.",
    category: "ai",
    authType: "apikey",
    color: "#cc785c",
    bgColor: "#1a0e09",
    iconText: "Cl",
    apiKeyLabel: "Anthropic API Key",
    apiKeyPlaceholder: "sk-ant-...",
    docsUrl: "https://console.anthropic.com/settings/keys",
  },
  {
    slug: "huggingface",
    name: "Hugging Face",
    description: "Run open-source ML models for NLP, image recognition, audio, and more via the Inference API.",
    category: "ai",
    authType: "apikey",
    color: "#ffd21e",
    bgColor: "#1a1500",
    iconText: "HF",
    apiKeyLabel: "Hugging Face Token",
    apiKeyPlaceholder: "hf_...",
    docsUrl: "https://huggingface.co/settings/tokens",
  },

  // ── Communication ─────────────────────────────────────────────────────────
  {
    slug: "gmail",
    name: "Gmail",
    description: "Send, read, and manage emails through your Gmail account in any workflow.",
    category: "communication",
    authType: "oauth",
    color: "#ea4335",
    bgColor: "#2c1210",
    iconText: "Gm",
    oauthConfig: {
      authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: [
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/userinfo.email",
      ],
      clientIdEnv: "GOOGLE_CLIENT_ID",
      clientSecretEnv: "GOOGLE_CLIENT_SECRET",
      tokenExchange: "body",
      additionalAuthParams: { access_type: "offline", prompt: "consent" },
    },
  },
  {
    slug: "slack",
    name: "Slack",
    description: "Post messages, create channels, and interact with your Slack workspace automatically.",
    category: "communication",
    authType: "oauth",
    color: "#4a154b",
    bgColor: "#1a0a1b",
    iconText: "Sl",
    oauthConfig: {
      authorizationUrl: "https://slack.com/oauth/v2/authorize",
      tokenUrl: "https://slack.com/api/oauth.v2.access",
      scopes: ["chat:write", "channels:read", "users:read"],
      clientIdEnv: "SLACK_CLIENT_ID",
      clientSecretEnv: "SLACK_CLIENT_SECRET",
      tokenExchange: "body",
    },
  },
  {
    slug: "discord",
    name: "Discord",
    description: "Send messages and manage Discord servers with bot or webhook integrations.",
    category: "communication",
    authType: "oauth",
    color: "#5865f2",
    bgColor: "#0e1030",
    iconText: "Dc",
    oauthConfig: {
      authorizationUrl: "https://discord.com/api/oauth2/authorize",
      tokenUrl: "https://discord.com/api/oauth2/token",
      scopes: ["identify", "email", "guilds"],
      clientIdEnv: "DISCORD_CLIENT_ID",
      clientSecretEnv: "DISCORD_CLIENT_SECRET",
      tokenExchange: "body",
    },
  },
  {
    slug: "telegram",
    name: "Telegram",
    description: "Send messages, files, and notifications through Telegram bots to users or groups.",
    category: "communication",
    authType: "apikey",
    color: "#26a5e4",
    bgColor: "#051525",
    iconText: "Tg",
    apiKeyLabel: "Bot Token",
    apiKeyPlaceholder: "123456:ABC-DEF...",
    docsUrl: "https://core.telegram.org/bots#how-do-i-create-a-bot",
  },
  {
    slug: "whatsapp",
    name: "WhatsApp",
    description: "Send WhatsApp messages via the Meta Cloud API to individuals or broadcast lists.",
    category: "communication",
    authType: "apikey",
    color: "#25d366",
    bgColor: "#041a0a",
    iconText: "WA",
    apiKeyLabel: "Meta Access Token",
    apiKeyPlaceholder: "EAA...",
    docsUrl: "https://developers.facebook.com/docs/whatsapp",
  },
  {
    slug: "twilio",
    name: "Twilio",
    description: "Send SMS, MMS, and make voice calls programmatically using the Twilio API.",
    category: "communication",
    authType: "apikey",
    color: "#f22f46",
    bgColor: "#200508",
    iconText: "Tw",
    apiKeyLabel: "Auth Token",
    apiKeyPlaceholder: "your_auth_token",
    docsUrl: "https://console.twilio.com",
  },
  {
    slug: "sendgrid",
    name: "SendGrid",
    description: "Send transactional and marketing emails at scale with advanced analytics and templates.",
    category: "communication",
    authType: "apikey",
    color: "#1a82e2",
    bgColor: "#020d1c",
    iconText: "SG",
    apiKeyLabel: "SendGrid API Key",
    apiKeyPlaceholder: "SG...",
    docsUrl: "https://app.sendgrid.com/settings/api_keys",
  },
  {
    slug: "resend",
    name: "Resend",
    description: "Developer-first email API for sending transactional emails with high deliverability.",
    category: "communication",
    authType: "apikey",
    color: "#ffffff",
    bgColor: "#111111",
    iconText: "Re",
    apiKeyLabel: "Resend API Key",
    apiKeyPlaceholder: "re_...",
    docsUrl: "https://resend.com/api-keys",
  },
  {
    slug: "mailchimp",
    name: "Mailchimp",
    description: "Manage email campaigns, audiences, and automations with the Mailchimp Marketing API.",
    category: "communication",
    authType: "apikey",
    color: "#ffe01b",
    bgColor: "#1a1500",
    iconText: "Mc",
    apiKeyLabel: "Mailchimp API Key",
    apiKeyPlaceholder: "your-api-key-us1",
    docsUrl: "https://mailchimp.com/developer/marketing/guides/quick-start/",
  },

  // ── Productivity ──────────────────────────────────────────────────────────
  {
    slug: "notion",
    name: "Notion",
    description: "Create, read, and update pages, databases, and blocks in Notion workspaces.",
    category: "productivity",
    authType: "oauth",
    color: "#ffffff",
    bgColor: "#1a1a1a",
    iconText: "No",
    oauthConfig: {
      authorizationUrl: "https://api.notion.com/v1/oauth/authorize",
      tokenUrl: "https://api.notion.com/v1/oauth/token",
      scopes: [],
      clientIdEnv: "NOTION_CLIENT_ID",
      clientSecretEnv: "NOTION_CLIENT_SECRET",
      tokenExchange: "basic_auth",
      additionalAuthParams: { owner: "user" },
    },
  },
  {
    slug: "google-sheets",
    name: "Google Sheets",
    description: "Read and write rows, manage spreadsheets, and trigger workflows from sheet changes.",
    category: "productivity",
    authType: "oauth",
    color: "#34a853",
    bgColor: "#0a2010",
    iconText: "GS",
    oauthConfig: {
      authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/userinfo.email",
      ],
      clientIdEnv: "GOOGLE_CLIENT_ID",
      clientSecretEnv: "GOOGLE_CLIENT_SECRET",
      tokenExchange: "body",
      additionalAuthParams: { access_type: "offline", prompt: "consent" },
    },
  },
  {
    slug: "google-drive",
    name: "Google Drive",
    description: "Upload, download, organize files and folders, and trigger workflows on Drive changes.",
    category: "productivity",
    authType: "oauth",
    color: "#4285f4",
    bgColor: "#050d1f",
    iconText: "GD",
    oauthConfig: {
      authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/userinfo.email",
      ],
      clientIdEnv: "GOOGLE_CLIENT_ID",
      clientSecretEnv: "GOOGLE_CLIENT_SECRET",
      tokenExchange: "body",
      additionalAuthParams: { access_type: "offline", prompt: "consent" },
    },
  },
  {
    slug: "dropbox",
    name: "Dropbox",
    description: "Upload, download, and manage files in Dropbox from your automated workflows.",
    category: "productivity",
    authType: "oauth",
    color: "#0061ff",
    bgColor: "#00071a",
    iconText: "Db",
    oauthConfig: {
      authorizationUrl: "https://www.dropbox.com/oauth2/authorize",
      tokenUrl: "https://api.dropboxapi.com/oauth2/token",
      scopes: ["files.content.write", "files.content.read"],
      clientIdEnv: "DROPBOX_CLIENT_ID",
      clientSecretEnv: "DROPBOX_CLIENT_SECRET",
      tokenExchange: "body",
      additionalAuthParams: { token_access_type: "offline" },
    },
  },
  {
    slug: "airtable",
    name: "Airtable",
    description: "Read and write records, manage tables, and build powerful database-driven workflows.",
    category: "productivity",
    authType: "apikey",
    color: "#18bfff",
    bgColor: "#021520",
    iconText: "At",
    apiKeyLabel: "Personal Access Token",
    apiKeyPlaceholder: "pat...",
    docsUrl: "https://airtable.com/create/tokens",
  },
  {
    slug: "jira",
    name: "Jira",
    description: "Create issues, update statuses, and manage sprints in Jira Software projects.",
    category: "productivity",
    authType: "apikey",
    color: "#0052cc",
    bgColor: "#000a1a",
    iconText: "Ji",
    apiKeyLabel: "Jira API Token",
    apiKeyPlaceholder: "your-api-token",
    docsUrl: "https://id.atlassian.com/manage-profile/security/api-tokens",
  },
  {
    slug: "linear",
    name: "Linear",
    description: "Create and update issues, manage cycles, and track engineering work in Linear.",
    category: "productivity",
    authType: "apikey",
    color: "#5e6ad2",
    bgColor: "#0a0b1a",
    iconText: "Li",
    apiKeyLabel: "Linear API Key",
    apiKeyPlaceholder: "lin_api_...",
    docsUrl: "https://linear.app/settings/api",
  },
  {
    slug: "trello",
    name: "Trello",
    description: "Create cards, move items between lists, and manage Trello boards automatically.",
    category: "productivity",
    authType: "apikey",
    color: "#0052cc",
    bgColor: "#000a1a",
    iconText: "Tr",
    apiKeyLabel: "Trello API Key",
    apiKeyPlaceholder: "your-api-key",
    docsUrl: "https://trello.com/app-key",
  },
  {
    slug: "asana",
    name: "Asana",
    description: "Create tasks, update projects, and manage team workflows in Asana.",
    category: "productivity",
    authType: "apikey",
    color: "#f06a6a",
    bgColor: "#1a0808",
    iconText: "As",
    apiKeyLabel: "Personal Access Token",
    apiKeyPlaceholder: "your-pat",
    docsUrl: "https://app.asana.com/0/my-apps",
  },
  {
    slug: "clickup",
    name: "ClickUp",
    description: "Create tasks, manage spaces, and automate project workflows in ClickUp.",
    category: "productivity",
    authType: "apikey",
    color: "#7b68ee",
    bgColor: "#0d0b1f",
    iconText: "Cu",
    apiKeyLabel: "ClickUp API Key",
    apiKeyPlaceholder: "your-api-key",
    docsUrl: "https://app.clickup.com/settings/apps",
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    description: "Manage contacts, deals, and companies in HubSpot CRM from your workflows.",
    category: "productivity",
    authType: "apikey",
    color: "#ff7a59",
    bgColor: "#1a0800",
    iconText: "Hs",
    apiKeyLabel: "Private App Token",
    apiKeyPlaceholder: "pat-na1-...",
    docsUrl: "https://developers.hubspot.com/docs/api/private-apps",
  },

  // ── Developer ─────────────────────────────────────────────────────────────
  {
    slug: "github",
    name: "GitHub",
    description: "Trigger workflows on push, pull requests, issues, and manage repos via the GitHub API.",
    category: "developer",
    authType: "oauth",
    color: "#f0f6fc",
    bgColor: "#161b22",
    iconText: "GH",
    oauthConfig: {
      authorizationUrl: "https://github.com/login/oauth/authorize",
      tokenUrl: "https://github.com/login/oauth/access_token",
      scopes: ["repo", "user:email"],
      clientIdEnv: "GITHUB_CLIENT_ID",
      clientSecretEnv: "GITHUB_CLIENT_SECRET",
      tokenExchange: "body",
    },
  },
  {
    slug: "stripe",
    name: "Stripe",
    description: "Handle payments, subscriptions, invoices, and webhooks with the Stripe API.",
    category: "developer",
    authType: "apikey",
    color: "#635bff",
    bgColor: "#0a091f",
    iconText: "St",
    apiKeyLabel: "Secret Key",
    apiKeyPlaceholder: "sk_live_...",
    docsUrl: "https://dashboard.stripe.com/apikeys",
  },
  {
    slug: "supabase",
    name: "Supabase",
    description: "Query databases, manage auth, call Edge Functions, and use Supabase Storage.",
    category: "developer",
    authType: "apikey",
    color: "#3ecf8e",
    bgColor: "#031a0e",
    iconText: "Sb",
    apiKeyLabel: "Service Role Key",
    apiKeyPlaceholder: "eyJ...",
    docsUrl: "https://supabase.com/dashboard/project/_/settings/api",
  },
  {
    slug: "vercel",
    name: "Vercel",
    description: "Deploy projects, manage domains, list deployments, and trigger builds via Vercel API.",
    category: "developer",
    authType: "apikey",
    color: "#ffffff",
    bgColor: "#111111",
    iconText: "Vc",
    apiKeyLabel: "Access Token",
    apiKeyPlaceholder: "your-token",
    docsUrl: "https://vercel.com/account/tokens",
  },
  {
    slug: "shopify",
    name: "Shopify",
    description: "Manage products, orders, customers, and inventory in your Shopify store.",
    category: "developer",
    authType: "apikey",
    color: "#96bf48",
    bgColor: "#0c1505",
    iconText: "Sh",
    apiKeyLabel: "Admin API Token",
    apiKeyPlaceholder: "shpat_...",
    docsUrl: "https://shopify.dev/docs/api/admin-rest",
  },
  {
    slug: "aws",
    name: "AWS",
    description: "Trigger Lambda functions, manage S3 buckets, send SNS/SQS messages, and more.",
    category: "developer",
    authType: "apikey",
    color: "#ff9900",
    bgColor: "#1a0d00",
    iconText: "AWS",
    apiKeyLabel: "Secret Access Key",
    apiKeyPlaceholder: "your-secret-key",
    docsUrl: "https://console.aws.amazon.com/iam",
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    description: "Manage DNS, deploy Workers, and use KV/R2 storage via the Cloudflare API.",
    category: "developer",
    authType: "apikey",
    color: "#f48120",
    bgColor: "#1a0d00",
    iconText: "CF",
    apiKeyLabel: "API Token",
    apiKeyPlaceholder: "your-api-token",
    docsUrl: "https://dash.cloudflare.com/profile/api-tokens",
  },
  {
    slug: "webhook",
    name: "Webhook",
    description: "Receive HTTP webhook events from any external service to trigger your workflows.",
    category: "developer",
    authType: "none",
    color: "#f97316",
    bgColor: "#1c0a02",
    iconText: "WH",
  },
  {
    slug: "http-request",
    name: "HTTP Request",
    description: "Make GET, POST, PUT, DELETE requests to any REST API endpoint from your workflows.",
    category: "developer",
    authType: "none",
    color: "#0ea5e9",
    bgColor: "#020d14",
    iconText: "HTTP",
  },

  // ── Database ──────────────────────────────────────────────────────────────
  {
    slug: "postgresql",
    name: "PostgreSQL",
    description: "Run queries, insert rows, and manage data in any PostgreSQL-compatible database.",
    category: "database",
    authType: "apikey",
    color: "#336791",
    bgColor: "#050f1a",
    iconText: "PG",
    apiKeyLabel: "Connection URL",
    apiKeyPlaceholder: "postgresql://user:pass@host:5432/db",
  },
  {
    slug: "mongodb",
    name: "MongoDB",
    description: "Query collections, insert documents, and aggregate data with MongoDB Atlas.",
    category: "database",
    authType: "apikey",
    color: "#47a248",
    bgColor: "#051205",
    iconText: "MG",
    apiKeyLabel: "Connection String",
    apiKeyPlaceholder: "mongodb+srv://...",
    docsUrl: "https://cloud.mongodb.com",
  },
  {
    slug: "redis",
    name: "Redis",
    description: "Get, set, and expire keys; publish to channels; and manage Redis data structures.",
    category: "database",
    authType: "apikey",
    color: "#ff4438",
    bgColor: "#1a0404",
    iconText: "RD",
    apiKeyLabel: "Redis URL",
    apiKeyPlaceholder: "redis://default:password@host:6379",
  },
  {
    slug: "mysql",
    name: "MySQL",
    description: "Execute queries, insert and update rows in any MySQL or MariaDB database.",
    category: "database",
    authType: "apikey",
    color: "#4479a1",
    bgColor: "#050f1a",
    iconText: "SQL",
    apiKeyLabel: "Connection URL",
    apiKeyPlaceholder: "mysql://user:pass@host:3306/db",
  },
];

export const CATEGORIES: { value: IntegrationCategory | "all"; label: string }[] = [
  { value: "all", label: "All" },
  { value: "ai", label: "AI" },
  { value: "communication", label: "Communication" },
  { value: "productivity", label: "Productivity" },
  { value: "developer", label: "Developer" },
  { value: "database", label: "Database" },
];

export function getIntegration(slug: string): IntegrationDefinition | undefined {
  return INTEGRATIONS.find((i) => i.slug === slug);
}
