import { z } from "zod";
import type { NodePlugin } from "../base-types";

export const TRIGGER_NODES: NodePlugin[] = [
  {
    id: "webhook-trigger",
    name: "Webhook Trigger",
    category: "trigger",
    group: "Triggers",
    icon: "webhook",
    color: "#ea580c",
    bgColor: "#431407",
    description: "Start workflow when an HTTP POST webhook is received",
    inputs: [],
    outputs: [{ id: "data", label: "Webhook Data", type: "object" }],
    configFields: [],
    zodSchema: z.object({}),
    execute: async (_, input) => ({ trigger: "webhook", data: input }),
  },
  {
    id: "manual-trigger",
    name: "Manual Trigger",
    category: "trigger",
    group: "Triggers",
    icon: "play",
    color: "#f97316",
    bgColor: "#431407",
    description: "Manually start the workflow from the dashboard",
    inputs: [],
    outputs: [{ id: "data", label: "Trigger Data", type: "object" }],
    configFields: [],
    zodSchema: z.object({}),
    execute: async (_, input) => ({ trigger: "manual", data: input }),
  },
  {
    id: "schedule-trigger",
    name: "Schedule Trigger",
    category: "trigger",
    group: "Triggers",
    icon: "clock",
    color: "#f59e0b",
    bgColor: "#451a03",
    description: "Run workflow on a cron schedule (e.g. every hour, every morning)",
    inputs: [],
    outputs: [{ id: "data", label: "Schedule Data", type: "object" }],
    configFields: [
      {
        key: "preset",
        label: "Schedule",
        type: "select",
        options: [
          { label: "Every minute", value: "* * * * *" },
          { label: "Every 5 minutes", value: "*/5 * * * *" },
          { label: "Every 15 minutes", value: "*/15 * * * *" },
          { label: "Every hour", value: "0 * * * *" },
          { label: "Every day at midnight", value: "0 0 * * *" },
          { label: "Every Monday at 9am", value: "0 9 * * 1" },
          { label: "Custom", value: "custom" },
        ],
        defaultValue: "0 * * * *",
      },
      {
        key: "cron",
        label: "Custom Cron Expression",
        type: "text",
        placeholder: "0 9 * * 1",
        description: "Cron expression (minute hour day month weekday)",
        condition: (v) => v.preset === "custom",
      },
      {
        key: "timezone",
        label: "Timezone",
        type: "text",
        placeholder: "UTC",
        defaultValue: "UTC",
        description: "IANA timezone e.g. America/New_York",
      },
    ],
    zodSchema: z.object({
      preset: z.string().optional(),
      cron: z.string().optional(),
      timezone: z.string().optional(),
    }),
    execute: async (config, input) => ({
      trigger: "schedule",
      cron: config.preset === "custom" ? config.cron : config.preset,
      timestamp: new Date().toISOString(),
      data: input,
    }),
  },
  {
    id: "interval-trigger",
    name: "Interval Trigger",
    category: "trigger",
    group: "Triggers",
    icon: "clock",
    color: "#84cc16",
    bgColor: "#1a2e05",
    description: "Run workflow repeatedly at a fixed interval (every N seconds/minutes/hours)",
    inputs: [],
    outputs: [{ id: "data", label: "Interval Data", type: "object" }],
    configFields: [
      {
        key: "interval",
        label: "Interval",
        type: "number",
        placeholder: "60",
        defaultValue: 60,
        min: 1,
        description: "Number of seconds between runs",
      },
    ],
    zodSchema: z.object({ interval: z.coerce.number().min(1).optional() }),
    execute: async (config, input) => ({
      trigger: "interval",
      interval: config.interval,
      timestamp: new Date().toISOString(),
      data: input,
    }),
  },
  {
    id: "gmail-trigger",
    name: "Gmail: New Email",
    category: "trigger",
    group: "Triggers",
    icon: "gmail",
    color: "#ea4335",
    bgColor: "#2c1210",
    description: "Trigger when a new email arrives matching a filter",
    inputs: [],
    outputs: [{ id: "email", label: "Email Data", type: "object" }],
    configFields: [
      {
        key: "query",
        label: "Gmail Filter Query",
        type: "text",
        placeholder: "from:boss@company.com",
        description: "Gmail search syntax (leave blank for all new emails)",
      },
      {
        key: "labels",
        label: "Label",
        type: "text",
        placeholder: "INBOX",
        defaultValue: "INBOX",
      },
    ],
    zodSchema: z.object({ query: z.string().optional(), labels: z.string().optional() }),
    execute: async (_, input) => ({ trigger: "gmail", data: input }),
  },
];
